name: Unit tests

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'
    paths-ignore:
      - '**/*.md'  # Ignore changes to all Markdown files
    types: [opened, synchronize, reopened]

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-20.04
    if: >
      (
        startsWith(github.head_ref, 'feature/') && github.base_ref == 'develop'
      ) || 
      (
        github.head_ref == 'develop' && github.base_ref == 'main'
      )
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install dependencies and run tests
        run: |
          mvn clean test | tee results.log
          test ${PIPESTATUS[0]} -eq 0
        
      - name: Print results
        run: |
           echo -e "\e[0;36m$(grep -A 3 '\[INFO\] Results:' results.log | sed -n '4p' | sed 's/^[[:space:]]*//')\e[0m"
           rm results.log
