name: Unit tests

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'
    paths-ignore:
      - '**/*.md'  # Ignore changes to all Markdown files
    types: [opened, synchronize, reopened]

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-20.04
    if: >
      (
        github.event.pull_request.head.ref == 'develop' && github.event.pull_request.base.ref == 'main'
      ) || 
      (
        startsWith(github.event.pull_request.head.ref, 'feature/') && github.event.pull_request.base.ref == 'develop'
      )
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      #- name: Print working directory
        #run: pwd

      #- name: List files in the repository
        #run: ls -R ./src/test/java

      - name: Install dependencies and run tests
        run: |
          mvn clean test | tee results.log
          test ${PIPESTATUS[0]} -eq 0
        
      - name: Print Surefire report
        run: |
           grep -A 2 '\[INFO\] Results:' results.log
           rm results.log
