name: Unit tests

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'
    paths-ignore:
      - 'README.md'  # Optional: Ignore changes to specific files like README.md
    types: [opened, synchronize, reopened]  # Specify the types of PR events to trigger the workflow

jobs:
  tests:
    if: >
      (
        startsWith(github.head_ref, 'feature/') && github.base_ref == 'develop'
      ) || 
      (
        github.head_ref == 'develop' && github.base_ref == 'main'
      )
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      #- name: Print working directory
        #run: pwd

      #- name: List files in the repository
        #run: ls -R ./src/test/java

      - name: Install dependencies and run tests
        run: |
          mvn clean test | tee results.log
          test ${PIPESTATUS[0]} -eq 0
        
      - name: Print Surefire report
        run: |
           grep -A 2 '\[INFO\] Results:' results.log
           rm results.log
