name: Unit tests

on:
  pull_request:
    types: [closed, synchronize, opened ]
    branches:
      - main
      - develop
    paths-ignore:
      - '**/*.md'

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Force failure
        run: |
          exit 1

      - name: Test fail condition
        if: ${{ failure() }}
        run: |
          echo "Job failed"

      - name: Test ok condition
        if: ${{ success() }}
        run: |
          echo "Job OK"
